language: python
python:
- 3.5
- pypy3.5
- 3.6
- 3.7
- 3.8-dev
sudo: false
dist: xenial
matrix:
  include:
  - os: osx
    language: generic
    env: MACPYTHON=3.6.3
  - os: linux
    language: python
    python: 3.6
    env: CHECK_DOCS=1
  - os: linux
    language: python
    python: 3.6
    env: CHECK_FORMATTING=1
script:
- ci/travis.sh
